apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: test-secret
  namespace: default
spec:
  encryptedData:
    password: AgAFw7mm+3U2sYZNqg9iePNgjdhomEO61nLjB0+h0VUqAIh+NOqfsHqnw8Em+9vzggkrlxw7FixheXDTKi1yzHkVgH+aDBd8AT3ieTk2y2VE2KdHYQRMd18jl9N3V2xhHn1ryq42C4jOrUQRT8Zpb0QxzzazeuE7ix0ireav0r8rj2mo1fkbEjorn3VrXYXTZ+26OB4zYJvbKP9Q+PqqHEltsd0Pmg1P1nj9RMm44bWe7XJ2CGlbjW8ncVOTCTdqHLT//IZHl9bo1GXH3f4/38k71LLqVZ9dmrJna5sCa/7guVFvwjBWsu63sVS86Pk3/nqxQZbnVr2ycDrPtFbORPfKs4GXJyTysQ95bhy7OxCtsdvizyJPR68k3wnkKWfIZDP59j41RG0MHayBSCaeQ0cV8KknTn2o7oWyha3Iw0Jul7d09HjfrHZbXydiBkX2SOnAvZEdTzMp0XRyYtJA7BogvyfUP7at0qunJTqmH8Cr/xMg3OM6suUoxjTjmhdnb1CWGzAASpt9gfHYteCNrYvbjTLFgrcfOqFFUt//ksvvZmWxtZNq4Wr/W68tPQ73qFH3+Cp/rs2OfJlcP3L1B1TAbn8S5fDSbeGjexpbJpqU64bfREu76iYGiqrY/eoUThrZm/jNtLWIMXuDEj2tkTtRMaLOmAL/QBYkv6a5wiDDwrTaUkFuHAvV9019tJuwy1mRVIo=
    username: AgBUFxgkJL3+TBktKBfBU+rnPLtL5/6u/GF9eQtc/S7VK9OYpd40phgzGxa+JFSg7Unmmvpz/4W3KELiJxxE0kjPZq7eYnWL6t3kMXEaViC1NuhPDvI4zMcHxgh6deG5HhKDQ+SdqyFDHL5/xF50vhbnUUi1V9HeEDO8xr6HBfROO9yzFgHQ6JXQJumUpLtKfjDL5FYjoOogNzNQJM6WoeN6hdZ+EhZ4IwOYw3XVGO7WLwMstmnGR5HYegG99eIYlxzB7UTtDK4g9xw1QOJlnGU34dyjQ4pI3eIIhr0/D25fnm4FsvXjUv1VhB7cqzBCYG0XJ+dbuGiAoM+xrdXQdegbWL8CN354WckPPUyX7NRQCbYMLY499zRVDYAaXDjj7BxBcdBQsqX9ClhngoTLGLe+MU25PH+elWhrqlzPRUwUYKZK/rj5HYfeVNvyjxb3Gi/a1OPfLyaetN88JXIQkHoy7jANrKNCf2IBdZQYqjL+B4FdrqDPxwf/mJuz7UMriihn5sL3IxhBrlFWhUkgA3pqkC41mcU0NznTbGKBxcaYWCOQGr3uUCQgwEn3J+q0GFDLdEXZPub/xmhbhO67GMxrxpsqgM9tqxuApoJLcnx5yBOheFCgJpKjoVBcPSWxiT1p2V+T6Avihy7jMRNwKCM/N72r8WdbnaTvvwbD/wFMrXBdAC40gEch3FafnLd9Fge1a4A=
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: test-secret
      namespace: default

